{
 "title": "Advanced Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "ExternalTasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ExternalTasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "externaltask_active{instance=\"host.docker.internal:8080\"}",
     "legendFormat": "Active ExternalTasks"
    },
    {
     "expr": "externaltask_locked{instance=\"host.docker.internal:8080\"}",
     "legendFormat": "Locked ExternalTasks"
    },
    {
     "expr": "externaltask_notlocked{instance=\"host.docker.internal:8080\"}",
     "legendFormat": "Not Locked ExternalTasks"
    }
   ]
  },
  {
   "title": "ExternalTask High Priority",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "externaltask_highpriority{instance=\"host.docker.internal:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "External Task No Retries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "externaltask_noretries{instance=\"host.docker.internal:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Timer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Timer Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "timer_count{instance=\"host.docker.internal:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time Executable",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 10 },
   "targets": [
    {
     "expr": "timer_executable{instance=\"host.docker.internal:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Comparison Timer Count & Executable",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 10, "y": 10 },
   "targets": [
    {
     "expr": "timer_count{instance=\"host.docker.internal:8080\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "timer_executable{instance=\"host.docker.internal:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Process Instances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Process Instances",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "processinstances_count{instance=\"host.docker.internal:8080\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "processinstances_completed{instance=\"host.docker.internal:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Incidents", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Incident Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "incidents_count{instance=\"host.docker.internal:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}