{
 "title": "Performance Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Job Executor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Job Executor Threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "executor_active_threads{name=\"camundaTaskExecutor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job Executor Pool Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "executor_pool_size_threads{name=\"camundaTaskExecutor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job Executor Pool Core Threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 3, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "executor_pool_core_threads{name=\"camundaTaskExecutor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job Executor completed jobs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 11, "y": 1 },
   "targets": [
    {
     "expr": "executor_completed_tasks_total{name=\"camundaTaskExecutor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "JDBC Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "jdbc_connections_min{instance=\"host.docker.internal:8080\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jdbc_connections_max{instance=\"host.docker.internal:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hikari Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 9 },
   "targets": [
    {
     "expr": "hikaricp_connections{instance=\"host.docker.internal:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hikari Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "hikaricp_connections_active{instance=\"host.docker.internal:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Hardware", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Disc Space Availability",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "disk_total_bytes{instance=\"host.docker.internal:8080\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "disk_free_bytes{instance=\"host.docker.internal:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 17 },
   "targets": [
    {
     "expr": "process_cpu_usage{instance=\"host.docker.internal:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}